//! `#[derive(OpParamsDoc)]`: harvest doc comments off an op's param struct into runtime-introspectable
//! help strings, so a harness author never hand-types the field-help table that
//! `OpDef::with_help(description, field_docs)` (phase 2) consumes.
//!
//! The derive emits an inherent impl with two associated fns:
//!
//! - `fn field_docs() -> Vec<(&'static str, &'static str)>` — one `(field_name, doc)` pair per
//!   named field **that carries a doc comment**. Fields with no `///` are omitted (not emitted with
//!   an empty string), so the table reflects only what the author actually documented.
//! - `fn doc() -> Option<&'static str>` — the struct-level doc comment (all `///` lines joined),
//!   or `None` when the struct is undocumented. This feeds `with_help`'s `description` argument.
//!
//! Doc-comment handling mirrors how `///` desugars: each `///` line becomes a separate
//! `#[doc = "..."]` attribute with a leading space, so we trim every line and join a field's
//! multiple lines with a single space into one string.
//!
//! ```ignore
//! #[derive(OpParamsDoc)]
//! /// Move funds between two accounts.
//! struct TransferParams {
//!     /// Source account id.
//!     from: String,
//!     /// Destination account id.
//!     to: String,
//!     amount: u128, // undocumented -> not in field_docs()
//! }
//! // TransferParams::doc()        == Some("Move funds between two accounts.")
//! // TransferParams::field_docs() == vec![("from", "Source account id."),
//! //                                       ("to",   "Destination account id.")]
//! ```

use proc_macro2::TokenStream;
use quote::quote;
use syn::{Attribute, Data, DeriveInput, Expr, ExprLit, Fields, Lit, Meta};

/// Expand `#[derive(OpParamsDoc)]` over `input`.
///
/// Requires a struct with named fields; enums, tuple/unit structs, and unions produce a
/// `syn::Error` (never a panic).
pub fn expand(input: TokenStream) -> syn::Result<TokenStream> {
    let input: DeriveInput = syn::parse2(input)?;

    let data = match &input.data {
        Data::Struct(s) => s,
        Data::Enum(_) | Data::Union(_) => {
            return Err(syn::Error::new_spanned(
                &input.ident,
                "OpParamsDoc can only be derived for a struct with named fields",
            ));
        }
    };

    let named = match &data.fields {
        Fields::Named(named) => named,
        Fields::Unnamed(_) | Fields::Unit => {
            return Err(syn::Error::new_spanned(
                &input.ident,
                "OpParamsDoc requires named fields (tuple and unit structs are not supported)",
            ));
        }
    };

    // Struct-level doc -> `doc()`.
    let struct_doc = collect_doc(&input.attrs);
    let struct_doc_tokens = match struct_doc {
        Some(d) => quote! { ::core::option::Option::Some(#d) },
        None => quote! { ::core::option::Option::None },
    };

    // Per-field docs -> `field_docs()`, omitting undocumented fields.
    let pairs = named.named.iter().filter_map(|field| {
        let doc = collect_doc(&field.attrs)?;
        let name = field.ident.as_ref()?.to_string();
        Some(quote! { (#name, #doc) })
    });

    let ident = &input.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    Ok(quote! {
        #[automatically_derived]
        impl #impl_generics #ident #ty_generics #where_clause {
            /// Struct-level doc comment (joined), or `None` if undocumented. Generated by `#[derive(OpParamsDoc)]`.
            pub fn doc() -> ::core::option::Option<&'static str> {
                #struct_doc_tokens
            }

            /// `(field_name, doc)` for each documented named field. Generated by `#[derive(OpParamsDoc)]`.
            pub fn field_docs() -> ::std::vec::Vec<(&'static str, &'static str)> {
                ::std::vec![ #(#pairs),* ]
            }
        }
    })
}

/// Join the `#[doc = "..."]` attributes on `attrs` into one string (each line trimmed, joined by a
/// single space), or `None` if there are no doc attributes.
///
/// `///` desugars to one `#[doc = " ..."]` per line with a leading space, so trimming per line and
/// space-joining reconstructs a single readable sentence from a multi-line comment.
fn collect_doc(attrs: &[Attribute]) -> Option<String> {
    let mut lines: Vec<String> = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        if let Meta::NameValue(nv) = &attr.meta {
            if let Expr::Lit(ExprLit {
                lit: Lit::Str(s), ..
            }) = &nv.value
            {
                lines.push(s.value().trim().to_string());
            }
        }
    }
    if lines.is_empty() {
        return None;
    }
    Some(lines.join(" ").trim().to_string())
}
