// Tronbox config for compiling the Solidity example contracts with TRON's solc fork (tronc).
//
// Compile-only: no networks/keys are needed. The sources are copied into ./generated by
// scripts/prepare-contracts.sh (gitignored), and artifacts land in ./build (gitignored).
//
// The example contracts are dependency-free and target ^0.8.24, so no viaIR / cancun /
// import remappings are required (unlike the OpenZeppelin-heavy euclid-solidity-contracts repo).
module.exports = {
    networks: {},
    contracts_directory: './generated',
    contracts_build_directory: './build',
    compilers: {
        solc: {
            version: '0.8.25',
            settings: {
                optimizer: { enabled: true, runs: 200 },
            },
        },
    },
};
