//! Cross-VM `Counter` wrapper: deploy, increment, and read a count identically on any VM.
//!
//! One wrapper, three per-VM hook implementations, reused by both the plain cross-VM test
//! (`cross_vm/counter.rs`) and the property-testing harness (`harness/counter.rs`).
//!
//! The `CounterSpec` trait below declares the logical methods once; `#[cross_vm_contract(Counter)]`
//! generates the `Counter` struct, its constructors, the hook forwarders, and a VM-dispatching
//! `impl CounterSpec for Counter` that calls the matching `cw_*` / `evm_*` / `svm_*` hook (firing
//! before/after hooks for methods that return an `AppResponse`). Only the per-VM hooks below are
//! hand-written.

use cross_vm_framework::prelude::*;

use cross_vm_solana::Address as SvmAddress;
use cross_vm_solidity::Bytes;
use solana_instruction::{AccountMeta, Instruction};

// Contract bindings come from `cross-vm-common`; these module aliases and constant re-bindings let
// the wrapper body below stay unchanged while sourcing every ABI, message type, and Solana
// constant from the one shared place. `cosmos_counter` re-exports `ExecuteMsgFns` / `QueryMsgFns`,
// so the typed calls in the hooks resolve unchanged.
use cross_vm_common::mocks::counter::{
    cw as cosmos_counter, evm as evm_counter, svm, tron as tron_counter,
};

const SOLANA_PROGRAM_ID: &str = svm::PROGRAM_ID;
const DISC_INITIALIZE: [u8; 8] = svm::DISC_INITIALIZE;
const DISC_INCREMENT: [u8; 8] = svm::DISC_INCREMENT;
const COUNTER_SO: &[u8] = svm::PROGRAM_SO;

/// The cross-VM counter's logical methods. `#[cross_vm_contract(Counter)]` turns this into the
/// `Counter` wrapper: struct, constructors, hook forwarders, and the VM dispatchers.
///
/// `increment` returns an `AppResponse`, so its dispatcher fires before/after hooks; `setup`
/// and `count` do not.
#[cross_vm_contract(Counter)]
pub trait CounterSpec {
    /// Deploy the counter and initialize its count to zero, signed by wallet `wallet`.
    async fn setup(&self, wallet: &str);
    /// Increment the count by one, signed by wallet `wallet`.
    async fn increment(&self, wallet: &str) -> AppResponse<()>;
    /// Read the current count.
    async fn count(&self) -> u64;
}

impl Counter {
    // ----- CosmWasm hooks -----
    async fn cw_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        let chain = self.base.cosmwasm()?;
        let code_id = chain.store_code(cosmos_counter::contract()).await?;
        let addr = chain
            .instantiate(
                code_id,
                cosmos_counter::InstantiateMsg {},
                WalletLabel::wrap(wallet),
                &[],
                "counter",
            )
            .await?;
        self.base.set_address(Account::CosmWasm(addr));
        Ok(())
    }

    async fn cw_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        // Typed call generated by `CwExecuteFns`: `increment(wallet)` builds the message and
        // executes it against the bound contract address (Layer 2).
        use cosmos_counter::ExecuteMsgFns;
        let raw = self
            .base
            .cosmwasm()?
            .contract(self.base.cw_addr()?)
            .increment(wallet)
            .await?;
        Ok(AppResponse::cosmwasm((), raw))
    }

    async fn cw_count(&self) -> Result<u64, CrossVmError> {
        // Typed call generated by `CwQueryFns`: `get_count()` queries and decodes `CountResponse`.
        use cosmos_counter::QueryMsgFns;
        let resp = self
            .base
            .cosmwasm()?
            .contract(self.base.cw_addr()?)
            .get_count()
            .await?;
        Ok(resp.count)
    }

    // ----- EVM hooks -----
    async fn evm_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        let chain = self.base.evm()?;
        let addr = chain
            .deploy_create(
                evm_counter::Counter::BYTECODE.clone(),
                Bytes::new(),
                WalletLabel::wrap(wallet),
            )
            .await?;
        self.base.set_address(Account::Evm(addr));
        Ok(())
    }

    async fn evm_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        use alloy::sol_types::SolCall;
        let chain = self.base.evm()?;
        let addr = self.base.evm_addr()?;
        let calldata = Bytes::from(evm_counter::Counter::incrementCall {}.abi_encode());
        let exec = chain
            .call(&addr, calldata, WalletLabel::wrap(wallet))
            .await?;
        Ok(AppResponse::evm((), exec.output, exec.logs))
    }

    async fn evm_count(&self) -> Result<u64, CrossVmError> {
        use alloy::sol_types::SolCall;
        let chain = self.base.evm()?;
        let addr = self.base.evm_addr()?;
        let out = chain
            .static_call(
                &addr,
                Bytes::from(evm_counter::Counter::countCall {}.abi_encode()),
            )
            .await?;
        let n = evm_counter::Counter::countCall::abi_decode_returns(&out).map_err(|e| {
            CrossVmError::Query {
                kind: ChainKind::Evm,
                reason: e.to_string(),
            }
        })?;
        Ok(n.saturating_to::<u64>())
    }

    // ----- Tron hooks (deploys tronc-compiled bytecode; ABI bindings reuse the EVM build) -----
    async fn tron_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        let chain = self.base.tron()?;
        let addr = chain
            .deploy_create(
                tron_counter::Counter::BYTECODE.clone(),
                Bytes::new(),
                WalletLabel::wrap(wallet),
            )
            .await?;
        self.base.set_address(Account::Tron(addr));
        Ok(())
    }

    async fn tron_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        use alloy::sol_types::SolCall;
        let chain = self.base.tron()?;
        let addr = self.base.tron_addr()?;
        let calldata = Bytes::from(evm_counter::Counter::incrementCall {}.abi_encode());
        let exec = chain
            .call(&addr, calldata, WalletLabel::wrap(wallet))
            .await?;
        Ok(AppResponse::tron((), exec.output, exec.logs))
    }

    async fn tron_count(&self) -> Result<u64, CrossVmError> {
        use alloy::sol_types::SolCall;
        let chain = self.base.tron()?;
        let addr = self.base.tron_addr()?;
        let out = chain
            .static_call(
                &addr,
                Bytes::from(evm_counter::Counter::countCall {}.abi_encode()),
            )
            .await?;
        let n = evm_counter::Counter::countCall::abi_decode_returns(&out).map_err(|e| {
            CrossVmError::Query {
                kind: ChainKind::Tron,
                reason: e.to_string(),
            }
        })?;
        Ok(n.saturating_to::<u64>())
    }

    // ----- Solana hooks -----
    async fn svm_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        let chain = self.base.solana()?;
        let program_id = SvmAddress::from_str_const(SOLANA_PROGRAM_ID);
        chain
            .add_program_at(program_id, COUNTER_SO.to_vec())
            .await?;
        let user = chain.wallet_address(WalletLabel::wrap(wallet)).await?;
        let (pda, _bump) =
            SvmAddress::find_program_address(&[b"counter", user.as_ref()], &program_id);
        let ix = Instruction::new_with_bytes(
            program_id,
            &DISC_INITIALIZE,
            vec![
                AccountMeta::new(pda, false),
                AccountMeta::new(user, true),
                AccountMeta::new_readonly(solana_system_interface::program::ID, false),
            ],
        );
        chain
            .send_transaction(vec![ix], WalletLabel::wrap(wallet))
            .await?;
        self.base.set_address(Account::Svm(pda));
        Ok(())
    }

    async fn svm_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        let chain = self.base.solana()?;
        let program_id = SvmAddress::from_str_const(SOLANA_PROGRAM_ID);
        let pda = self.base.svm_addr()?;
        let user = chain.wallet_address(WalletLabel::wrap(wallet)).await?;
        let ix = Instruction::new_with_bytes(
            program_id,
            &DISC_INCREMENT,
            vec![
                AccountMeta::new(pda, false),
                AccountMeta::new_readonly(user, true),
            ],
        );
        let meta = chain
            .send_transaction(vec![ix], WalletLabel::wrap(wallet))
            .await?;
        Ok(AppResponse::solana((), meta))
    }

    async fn svm_count(&self) -> Result<u64, CrossVmError> {
        let chain = self.base.solana()?;
        let pda = self.base.svm_addr()?;
        let acct = chain
            .get_account(&pda)
            .await?
            .ok_or_else(|| CrossVmError::Query {
                kind: ChainKind::Svm,
                reason: "counter account not found".into(),
            })?;
        let bytes = acct.data.get(8..16).ok_or_else(|| CrossVmError::Query {
            kind: ChainKind::Svm,
            reason: "counter account too small".into(),
        })?;
        let arr: [u8; 8] = bytes.try_into().expect("8 bytes");
        Ok(u64::from_le_bytes(arr))
    }
}
