//! CosmWasm counter bindings: message types (with the `*MsgFns` typed-call helpers) and the
//! in-process `cw-multi-test` contract factory.

use cosmwasm_std::Empty;
use cw_multi_test::{Contract, ContractWrapper};

// `ExecuteMsgFns` / `QueryMsgFns` are generated by the `CwExecuteFns` / `CwQueryFns` derives on
// the message enums (counter's `cross-vm` feature). Leading `::` disambiguates the extern crate
// from this crate's `mocks::counter` module under uniform-path resolution.
pub use ::counter::{
    CountResponse, CounterContract, ExecuteMsg, ExecuteMsgFns, InstantiateMsg, QueryMsg, QueryMsgFns,
};

/// A `cw-multi-test` wrapper over the counter contract's entry points, for in-process deployment.
pub fn contract() -> Box<dyn Contract<Empty, Empty>> {
    Box::new(ContractWrapper::new(
        ::counter::execute,
        ::counter::instantiate,
        ::counter::query,
    ))
}

/// The Docker-optimized counter `.wasm`, for on-chain (RPC) deploys. Gated behind `cw-artifacts`
/// because the artifact is gitignored and built locally, not present in CI.
#[cfg(feature = "cw-artifacts")]
pub const COUNTER_WASM: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../contracts/cosmwasm/artifacts/counter.wasm"
));
