//! CosmWasm collateralized-debt vault: the canonical entry points wrapping [`contract`] logic.
//!
//! `execute` threads `info.sender` into the logic so ledgers are keyed by the caller. Consumed
//! both as a wasm artifact and, in cross-VM tests, as an rlib via `cw-multi-test`'s
//! `ContractWrapper`.

mod contract;
mod msg;
mod state;

pub use crate::msg::{AmountResponse, ExecuteMsg, InstantiateMsg, QueryMsg, VersionResponse};
// Typed message-handle traits generated by the `cross-vm` feature's derives.
#[cfg(feature = "cross-vm")]
pub use crate::msg::{ExecuteMsgFns, QueryMsgFns, VaultContract};

use cosmwasm_std::{entry_point, Binary, Deps, DepsMut, Env, MessageInfo, Response, StdResult};

#[entry_point]
pub fn instantiate(
    deps: DepsMut,
    _env: Env,
    _info: MessageInfo,
    msg: InstantiateMsg,
) -> StdResult<Response> {
    contract::instantiate(deps, msg)
}

#[entry_point]
pub fn execute(
    deps: DepsMut,
    _env: Env,
    info: MessageInfo,
    msg: ExecuteMsg,
) -> StdResult<Response> {
    contract::execute(deps, info.sender, msg)
}

#[entry_point]
pub fn query(deps: Deps, _env: Env, msg: QueryMsg) -> StdResult<Binary> {
    contract::query(deps, msg)
}
