//! Chain-agnostic `Counter`: one logical contract, per-VM hooks.
//!
//! `#[cross_vm_contract(Counter)]` turns the `CounterSpec` trait into the `Counter` wrapper
//! (struct, constructors, hook forwarders) and a VM-dispatching `impl CounterSpec` that routes
//! each call to the matching `cw_*` / `evm_*` / `svm_*` hook below at runtime. Callers use only
//! the trait methods; the wrapper hides which VM it runs on.

use cross_vm_framework::prelude::*;
use cross_vm_solidity::Bytes;

use cross_vm_common::mocks::counter::cw::{self, COUNTER_WASM};
use cross_vm_common::mocks::counter::evm as evm_counter;

use crate::describe;

/// The cross-VM counter's logical methods.
#[cross_vm_contract(Counter)]
pub trait CounterSpec {
    /// Deploy the counter and initialize its count to zero, signed by `wallet`.
    async fn setup(&self, wallet: &str);
    /// Increment the count by one, signed by `wallet`.
    async fn increment(&self, wallet: &str) -> AppResponse<()>;
    /// Read the current count.
    async fn count(&self) -> u64;
}

impl Counter {
    // ----- CosmWasm hooks (live RPC: upload raw wasm, then instantiate) -----
    async fn cw_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        // One stateful handle threads `code_id` then address through the lifecycle: `store_code`
        // records the code id, its tx hash and its gas internally, `instantiate` records the
        // resulting address, tx hash and gas. The outer `Option`s below say which lifecycle steps
        // this handle ran; both ran here, so both are `Some`. The gas figure keeps the backend's
        // own `Option` nested inside: `Some(None)` would mean the step ran on a backend that
        // cannot meter, which is why `describe` renders it as unmetered rather than as zero.
        //
        // Every mutating step runs under `CwGasLimit::Estimated`: the node simulates the exact
        // message about to be broadcast and the declared limit is that figure scaled by the
        // chain's `gas_adjustment`. No hand-picked constant, and nothing to re-tune when the
        // contract grows.
        let contract = CwContract::<cw::CounterContract>::new(self.base.cosmwasm()?.clone())
            .store_code(
                COUNTER_WASM.to_vec(),
                WalletLabel::wrap(wallet),
                CwGasLimit::Estimated,
            )
            .await?
            .instantiate(
                cw::InstantiateMsg {},
                WalletLabel::wrap(wallet),
                &[],
                "counter",
                CwGasLimit::Estimated,
            )
            .await?;
        let addr = contract.address().expect("instantiated").clone();
        println!(
            "[cosmwasm] stored code id {} in tx {} ({})",
            contract.code_id().expect("stored"),
            contract.store_code_tx_hash().expect("stored"),
            describe(contract.store_code_gas().expect("stored").map(Cost::from)),
        );
        println!(
            "[cosmwasm] instantiated at {addr} in tx {} ({})",
            contract.instantiate_tx_hash().expect("instantiated"),
            describe(
                contract
                    .instantiate_gas()
                    .expect("instantiated")
                    .map(Cost::from)
            ),
        );
        self.base.set_address(Account::CosmWasm(addr));
        Ok(())
    }

    async fn cw_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        // Typed handle generated by `CwExecuteFns` (re-exported through the mocks `cw` module).
        // The derive emits `increment(wallet, gas)` and its forecast sibling
        // `estimate_increment(wallet)` (the same arguments minus the limit, because a forecast is
        // what you consult to pick one). Neither call names a message: the raw `ExecuteMsg` the
        // estimator used to need is now the derive's problem, not the call site's.
        use cw::ExecuteMsgFns;
        let counter = self
            .base
            .cosmwasm()?
            .contract_as::<cw::CounterContract>(self.base.cw_addr()?);

        // Forecast the op, then run it. `CwGasLimit::Estimated` resolves from this same
        // simulation, and the limit it declares sits above both figures, by `gas_adjustment`.
        let forecast = counter.estimate_increment(wallet).await?;
        let raw = counter.increment(wallet, CwGasLimit::Estimated).await?;

        // The payoff: a forecast and a receipt are one type (`Option<CwGas>` -> `Option<Cost>`), so
        // they print through the same renderer, side by side, with nothing reshaped to compare them.
        println!(
            "[cosmwasm] increment forecast: {} | receipt: {}",
            describe(forecast.map(Cost::from)),
            describe(raw.gas.map(Cost::from)),
        );
        Ok(AppResponse::cosmwasm(
            (),
            raw.response,
            raw.tx_hash,
            raw.gas,
        ))
    }

    async fn cw_count(&self) -> Result<u64, CrossVmError> {
        use cw::QueryMsgFns;
        let resp = self
            .base
            .cosmwasm()?
            .contract_as::<cw::CounterContract>(self.base.cw_addr()?)
            .get_count()
            .await?;
        Ok(resp.count)
    }

    // ----- EVM hooks (live RPC: deploy creation bytecode) -----
    async fn evm_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        let chain = self.base.evm()?;
        // `EvmGasLimit::Estimated` runs an `eth_estimateGas` and submits that figure scaled by the
        // chain's `gas_adjustment`, replacing the 30M-gas constant this used to inherit.
        let deployed = chain
            .deploy_create(
                evm_counter::Counter::BYTECODE.clone(),
                Bytes::new(),
                WalletLabel::wrap(wallet),
                EvmGasLimit::Estimated,
            )
            .await?;
        // Both EVM backends meter, so a figure is always there to print; only the fee can be
        // missing (the mock has no gas price to derive one from), and `Cost` renders that absence.
        println!(
            "[evm] deployed Counter at {} in tx {:#x} ({})",
            deployed.address,
            deployed.tx_hash,
            Cost::from(deployed.gas),
        );
        self.base.set_address(Account::Evm(deployed.address));
        Ok(())
    }

    async fn evm_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        use alloy::sol_types::SolCall;
        let chain = self.base.evm()?;
        let addr = self.base.evm_addr()?;
        let calldata = Bytes::from(evm_counter::Counter::incrementCall {}.abi_encode());

        // The forecast `EvmGasLimit::Estimated` is about to resolve from, printed next to the
        // receipt `main` prints for the same op. An estimate reports the gas the op is *billed*
        // (already net of the EIP-3529 refund) while the limit must cover what it *burns*, which
        // is what `gas_adjustment` supplies on top: expect the receipt to land near the forecast,
        // and the limit to sit above both.
        let forecast = chain
            .estimate_call(&addr, calldata.clone(), WalletLabel::wrap(wallet))
            .await?;
        println!("[evm] increment forecast: {}", Cost::from(forecast));

        let exec = chain
            .call(
                &addr,
                calldata,
                WalletLabel::wrap(wallet),
                EvmGasLimit::Estimated,
            )
            .await?;
        Ok(AppResponse::evm(
            (),
            exec.output,
            exec.logs,
            exec.tx_hash,
            exec.gas,
        ))
    }

    async fn evm_count(&self) -> Result<u64, CrossVmError> {
        use alloy::sol_types::SolCall;
        let chain = self.base.evm()?;
        let addr = self.base.evm_addr()?;
        let out = chain
            .static_call(
                &addr,
                Bytes::from(evm_counter::Counter::countCall {}.abi_encode()),
            )
            .await?;
        let n = evm_counter::Counter::countCall::abi_decode_returns(&out).map_err(|e| {
            CrossVmError::Query {
                kind: ChainKind::Evm,
                reason: e.to_string(),
            }
        })?;
        Ok(n.saturating_to::<u64>())
    }

    // ----- Solana hooks: this script targets EVM + Cosmos only, so they are never dispatched -----
    async fn svm_setup(&self, _wallet: &str) -> Result<(), CrossVmError> {
        unreachable!("deploy_counter targets EVM and Cosmos only")
    }
    async fn svm_increment(&self, _wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        unreachable!("deploy_counter targets EVM and Cosmos only")
    }
    async fn svm_count(&self) -> Result<u64, CrossVmError> {
        unreachable!("deploy_counter targets EVM and Cosmos only")
    }
}
