//! Chain-agnostic `Counter`: one logical contract, per-VM hooks.
//!
//! `#[cross_vm_contract(Counter)]` turns the `CounterSpec` trait into the `Counter` wrapper
//! (struct, constructors, hook forwarders) and a VM-dispatching `impl CounterSpec` that routes
//! each call to the matching `cw_*` / `evm_*` / `svm_*` hook below at runtime. Callers use only
//! the trait methods; the wrapper hides which VM it runs on.

use cross_vm_framework::prelude::*;
use cross_vm_solidity::Bytes;

use cross_vm_common::mocks::counter::cw::{self, COUNTER_WASM};
use cross_vm_common::mocks::counter::evm as evm_counter;

/// The cross-VM counter's logical methods.
#[cross_vm_contract(Counter)]
pub trait CounterSpec {
    /// Deploy the counter and initialize its count to zero, signed by `wallet`.
    async fn setup(&self, wallet: &str);
    /// Increment the count by one, signed by `wallet`.
    async fn increment(&self, wallet: &str) -> AppResponse<()>;
    /// Read the current count.
    async fn count(&self) -> u64;
}

impl Counter {
    // ----- CosmWasm hooks (live RPC: upload raw wasm, then instantiate) -----
    async fn cw_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        // One stateful handle threads `code_id` then address through the lifecycle: `store_code`
        // records the code id internally, `instantiate` records the resulting address.
        let contract = CwContract::<cw::CounterContract>::new(self.base.cosmwasm()?.clone())
            .store_code(COUNTER_WASM.to_vec(), WalletLabel::wrap(wallet))
            .await?
            .instantiate(
                cw::InstantiateMsg {},
                WalletLabel::wrap(wallet),
                &[],
                "counter",
            )
            .await?;
        let addr = contract.address().expect("instantiated").clone();
        println!(
            "[cosmwasm] stored code id {}, instantiated at {addr}",
            contract.code_id().expect("stored")
        );
        self.base.set_address(Account::CosmWasm(addr));
        Ok(())
    }

    async fn cw_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        // Typed handle generated by `CwExecuteFns` (re-exported through the mocks `cw` module).
        use cw::ExecuteMsgFns;
        let raw = self
            .base
            .cosmwasm()?
            .contract_as::<cw::CounterContract>(self.base.cw_addr()?)
            .increment(wallet)
            .await?;
        Ok(AppResponse::cosmwasm((), raw))
    }

    async fn cw_count(&self) -> Result<u64, CrossVmError> {
        use cw::QueryMsgFns;
        let resp = self
            .base
            .cosmwasm()?
            .contract_as::<cw::CounterContract>(self.base.cw_addr()?)
            .get_count()
            .await?;
        Ok(resp.count)
    }

    // ----- EVM hooks (live RPC: deploy creation bytecode) -----
    async fn evm_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        let chain = self.base.evm()?;
        let addr = chain
            .deploy_create(
                evm_counter::Counter::BYTECODE.clone(),
                Bytes::new(),
                WalletLabel::wrap(wallet),
            )
            .await?;
        println!("[evm] deployed Counter at {addr}");
        self.base.set_address(Account::Evm(addr));
        Ok(())
    }

    async fn evm_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        use alloy::sol_types::SolCall;
        let chain = self.base.evm()?;
        let addr = self.base.evm_addr()?;
        let calldata = Bytes::from(evm_counter::Counter::incrementCall {}.abi_encode());
        let exec = chain.call(&addr, calldata, WalletLabel::wrap(wallet)).await?;
        Ok(AppResponse::evm((), exec.output, exec.logs))
    }

    async fn evm_count(&self) -> Result<u64, CrossVmError> {
        use alloy::sol_types::SolCall;
        let chain = self.base.evm()?;
        let addr = self.base.evm_addr()?;
        let out = chain
            .static_call(
                &addr,
                Bytes::from(evm_counter::Counter::countCall {}.abi_encode()),
            )
            .await?;
        let n = evm_counter::Counter::countCall::abi_decode_returns(&out).map_err(|e| {
            CrossVmError::Query {
                kind: ChainKind::Evm,
                reason: e.to_string(),
            }
        })?;
        Ok(n.saturating_to::<u64>())
    }

    // ----- Solana hooks: this script targets EVM + Cosmos only, so they are never dispatched -----
    async fn svm_setup(&self, _wallet: &str) -> Result<(), CrossVmError> {
        unreachable!("deploy_counter targets EVM and Cosmos only")
    }
    async fn svm_increment(&self, _wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        unreachable!("deploy_counter targets EVM and Cosmos only")
    }
    async fn svm_count(&self) -> Result<u64, CrossVmError> {
        unreachable!("deploy_counter targets EVM and Cosmos only")
    }
}
