mod contract;
mod msg;
mod state;

pub use crate::msg::{CountResponse, ExecuteMsg, InstantiateMsg, QueryMsg, VersionResponse};
// Typed message-handle traits generated by the `cross-vm` feature's derives.
#[cfg(feature = "cross-vm")]
pub use crate::msg::{CounterContract, ExecuteMsgFns, QueryMsgFns};

use cosmwasm_std::{entry_point, Binary, Deps, DepsMut, Env, MessageInfo, Response, StdResult};

#[entry_point]
pub fn instantiate(
    deps: DepsMut,
    _env: Env,
    _info: MessageInfo,
    msg: InstantiateMsg,
) -> StdResult<Response> {
    contract::instantiate(deps, msg)
}

#[entry_point]
pub fn execute(
    deps: DepsMut,
    _env: Env,
    _info: MessageInfo,
    msg: ExecuteMsg,
) -> StdResult<Response> {
    contract::execute(deps, msg)
}

#[entry_point]
pub fn query(deps: Deps, _env: Env, msg: QueryMsg) -> StdResult<Binary> {
    contract::query(deps, msg)
}
