//! The shared `Counter` wrapper and its single-VM property-testing harness, reused by every example
//! test crate.
//!
//! [`Counter`] is one cross-VM wrapper (deploy, increment, read a count) generated by
//! `#[cross_vm_contract]`: the `CounterSpec` methods dispatch to the active VM's `cw_*`/`evm_*`/
//! `svm_*`/`tron_*` hook. Each hook block is gated behind its VM feature (`cw`/`evm`/`solana`/
//! `tron`), so a crate that enables only one VM compiles only that hook (the macro's default
//! `unimplemented!()` hooks cover the VMs it never dispatches). Bindings come from
//! [`crate::mocks::counter`].
//!
//! [`CounterHarness`] drives it: `apply` performs an op and advances a shadow model, `check` asserts
//! the on-chain count matches. [`setup_on`] builds the live env for the attribute-macro tests;
//! [`config_setup_with`] is the config-driven counterpart the `cross-vm` CLI registers, honoring a
//! `[[chain]]` declaration and falling back to a caller-supplied preset otherwise. Both take the
//! per-crate variance (chain label + preset) as parameters, since the VM presets are only in scope
//! for the crate that enabled that VM.

use std::rc::Rc;

use cross_vm_framework::config::{build_chain, SetupFuture, SetupRequest, Target};
use cross_vm_framework::prelude::*;
use cross_vm_macros::cross_vm_contract;
use serde::{Deserialize, Serialize};

use crate::wallets::fund_user;

#[cfg(feature = "cw")]
use crate::mocks::counter::cw as cosmos_counter;
#[cfg(feature = "evm")]
use crate::mocks::counter::evm as evm_counter;
#[cfg(feature = "solana")]
use crate::mocks::counter::svm;
#[cfg(feature = "tron")]
use crate::mocks::counter::tron as tron_counter;

#[cfg(feature = "solana")]
use cross_vm_solana::Address as SvmAddress;
#[cfg(feature = "solana")]
use solana_instruction::{AccountMeta, Instruction};

/// The wallet that signs deploys and increments in the single-VM harness.
const SIGNER: &str = "alice";

/// The cross-VM counter's logical methods. `#[cross_vm_contract(Counter)]` turns this into the
/// `Counter` wrapper: struct, constructors, hook forwarders, and the VM dispatchers.
///
/// `increment` returns an `AppResponse`, so its dispatcher fires before/after hooks; `setup` and
/// `count` do not.
#[cross_vm_contract(Counter)]
pub trait CounterSpec {
    /// Deploy the counter and initialize its count to zero, signed by wallet `wallet`.
    async fn setup(&self, wallet: &str);
    /// Increment the count by one, signed by wallet `wallet`.
    async fn increment(&self, wallet: &str) -> AppResponse<()>;
    /// Read the current count.
    async fn count(&self) -> u64;
}

// ----- CosmWasm hooks -----
#[cfg(feature = "cw")]
impl Counter {
    async fn cw_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        let chain = self.base.cosmwasm()?;
        let code_id = chain.store_code(cosmos_counter::contract()).await?;
        let addr = chain
            .instantiate(
                code_id,
                cosmos_counter::InstantiateMsg {},
                WalletLabel::wrap(wallet),
                &[],
                "counter",
            )
            .await?;
        self.base.set_address(Account::CosmWasm(addr));
        Ok(())
    }

    async fn cw_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        // Typed call generated by `CwExecuteFns`: `increment(wallet)` builds the message and
        // executes it against the bound contract address (Layer 2).
        use cosmos_counter::ExecuteMsgFns;
        let raw = self
            .base
            .cosmwasm()?
            .contract_as::<cosmos_counter::CounterContract>(self.base.cw_addr()?)
            .increment(wallet)
            .await?;
        Ok(AppResponse::cosmwasm((), raw))
    }

    async fn cw_count(&self) -> Result<u64, CrossVmError> {
        // Typed call generated by `CwQueryFns`: `get_count()` queries and decodes `CountResponse`.
        use cosmos_counter::QueryMsgFns;
        let resp = self
            .base
            .cosmwasm()?
            .contract_as::<cosmos_counter::CounterContract>(self.base.cw_addr()?)
            .get_count()
            .await?;
        Ok(resp.count)
    }
}

// ----- EVM hooks -----
#[cfg(feature = "evm")]
impl Counter {
    async fn evm_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        use cross_vm_solidity::Bytes;
        let chain = self.base.evm()?;
        let addr = chain
            .deploy_create(
                evm_counter::Counter::BYTECODE.clone(),
                Bytes::new(),
                WalletLabel::wrap(wallet),
            )
            .await?;
        self.base.set_address(Account::Evm(addr));
        Ok(())
    }

    async fn evm_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        use alloy::sol_types::SolCall;
        use cross_vm_solidity::Bytes;
        let chain = self.base.evm()?;
        let addr = self.base.evm_addr()?;
        let calldata = Bytes::from(evm_counter::Counter::incrementCall {}.abi_encode());
        let exec = chain
            .call(&addr, calldata, WalletLabel::wrap(wallet))
            .await?;
        Ok(AppResponse::evm((), exec.output, exec.logs))
    }

    async fn evm_count(&self) -> Result<u64, CrossVmError> {
        use alloy::sol_types::SolCall;
        use cross_vm_solidity::Bytes;
        let chain = self.base.evm()?;
        let addr = self.base.evm_addr()?;
        let out = chain
            .static_call(
                &addr,
                Bytes::from(evm_counter::Counter::countCall {}.abi_encode()),
            )
            .await?;
        let n = evm_counter::Counter::countCall::abi_decode_returns(&out).map_err(|e| {
            CrossVmError::Query {
                kind: ChainKind::Evm,
                reason: e.to_string(),
            }
        })?;
        Ok(n.saturating_to::<u64>())
    }
}

// ----- Tron hooks (deploys tronc-compiled bytecode; ABI bindings come from the tron mock) -----
#[cfg(feature = "tron")]
impl Counter {
    async fn tron_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        use cross_vm_tron::Bytes;
        let chain = self.base.tron()?;
        let addr = chain
            .deploy_create(
                tron_counter::Counter::BYTECODE.clone(),
                Bytes::new(),
                WalletLabel::wrap(wallet),
            )
            .await?;
        self.base.set_address(Account::Tron(addr));
        Ok(())
    }

    async fn tron_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        use alloy::sol_types::SolCall;
        use cross_vm_tron::Bytes;
        let chain = self.base.tron()?;
        let addr = self.base.tron_addr()?;
        let calldata = Bytes::from(tron_counter::Counter::incrementCall {}.abi_encode());
        let exec = chain
            .call(&addr, calldata, WalletLabel::wrap(wallet))
            .await?;
        Ok(AppResponse::tron((), exec.output, exec.logs))
    }

    async fn tron_count(&self) -> Result<u64, CrossVmError> {
        use alloy::sol_types::SolCall;
        use cross_vm_tron::Bytes;
        let chain = self.base.tron()?;
        let addr = self.base.tron_addr()?;
        let out = chain
            .static_call(
                &addr,
                Bytes::from(tron_counter::Counter::countCall {}.abi_encode()),
            )
            .await?;
        let n = tron_counter::Counter::countCall::abi_decode_returns(&out).map_err(|e| {
            CrossVmError::Query {
                kind: ChainKind::Tron,
                reason: e.to_string(),
            }
        })?;
        Ok(n.saturating_to::<u64>())
    }
}

// ----- Solana hooks -----
#[cfg(feature = "solana")]
impl Counter {
    async fn svm_setup(&self, wallet: &str) -> Result<(), CrossVmError> {
        let chain = self.base.solana()?;
        let program_id = SvmAddress::from_str_const(svm::PROGRAM_ID);
        chain
            .add_program_at(program_id, svm::PROGRAM_SO.to_vec())
            .await?;
        let user = chain.wallet_address(WalletLabel::wrap(wallet)).await?;
        let (pda, _bump) =
            SvmAddress::find_program_address(&[b"counter", user.as_ref()], &program_id);
        let ix = Instruction::new_with_bytes(
            program_id,
            &svm::DISC_INITIALIZE,
            vec![
                AccountMeta::new(pda, false),
                AccountMeta::new(user, true),
                AccountMeta::new_readonly(solana_system_interface::program::ID, false),
            ],
        );
        chain
            .send_transaction(vec![ix], WalletLabel::wrap(wallet))
            .await?;
        self.base.set_address(Account::Svm(pda));
        Ok(())
    }

    async fn svm_increment(&self, wallet: &str) -> Result<AppResponse<()>, CrossVmError> {
        let chain = self.base.solana()?;
        let program_id = SvmAddress::from_str_const(svm::PROGRAM_ID);
        let pda = self.base.svm_addr()?;
        let user = chain.wallet_address(WalletLabel::wrap(wallet)).await?;
        let ix = Instruction::new_with_bytes(
            program_id,
            &svm::DISC_INCREMENT,
            vec![
                AccountMeta::new(pda, false),
                AccountMeta::new_readonly(user, true),
            ],
        );
        let meta = chain
            .send_transaction(vec![ix], WalletLabel::wrap(wallet))
            .await?;
        Ok(AppResponse::solana((), meta))
    }

    async fn svm_count(&self) -> Result<u64, CrossVmError> {
        let chain = self.base.solana()?;
        let pda = self.base.svm_addr()?;
        let acct = chain
            .get_account(&pda)
            .await?
            .ok_or_else(|| CrossVmError::Query {
                kind: ChainKind::Svm,
                reason: "counter account not found".into(),
            })?;
        let bytes = acct.data.get(8..16).ok_or_else(|| CrossVmError::Query {
            kind: ChainKind::Svm,
            reason: "counter account too small".into(),
        })?;
        let arr: [u8; 8] = bytes.try_into().expect("8 bytes");
        Ok(u64::from_le_bytes(arr))
    }
}

/// One counter action. Externally tagged (serde default) so a TOML scenario step writes the unit
/// variant as a bare string, e.g. `op = "Increment"`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum CounterOp {
    /// Increment the count by one.
    Increment,
    /// Increment the count twice (exercises multi-call ops and a +2 model step).
    IncrementTwice,
}

/// The data-free kinds of [`CounterOp`], for per-kind fuzzing (`kinds = [...]` / `weights = {...}`).
#[derive(Clone, Copy, Debug, Serialize, Deserialize)]
pub enum CounterOpKind {
    /// See [`CounterOp::Increment`].
    Increment,
    /// See [`CounterOp::IncrementTwice`].
    IncrementTwice,
}

/// The invariants [`CounterHarness`] checks after each op.
///
/// `pub` only because it is `Harness::Invariant` for the `pub` [`CounterHarness`]; its variants
/// carry no data callers need.
#[derive(Clone, Debug)]
pub enum CounterInv {
    /// The on-chain count equals the shadow model (skipped until the first increment lands).
    CountMatchesModel,
}

/// Persisted state: where the counter is deployed, the shadow count, and the invariant precondition.
pub struct CounterWorld {
    label: String,
    addr: Account,
    model: u64,
    any_incremented: bool,
}

/// The single-VM counter [`Harness`]: increments the counter and checks the on-chain count against
/// a shadow model. One `apply` drives the scenario, fuzz, invariant, and endurance modes.
pub struct CounterHarness;

impl CounterHarness {
    /// Rebuild a `Counter` handle bound to the deployed instance.
    fn counter(ctx: &Ctx, world: &CounterWorld) -> Result<Counter, HarnessError> {
        let chain = ctx.chain(&world.label)?;
        Ok(Counter::instance(chain, world.addr.clone()))
    }
}

impl Harness for CounterHarness {
    type World = CounterWorld;
    type Operation = CounterOp;
    type Invariant = CounterInv;
    type OpKind = CounterOpKind;

    async fn apply(
        &self,
        ctx: &mut Ctx,
        w: &mut CounterWorld,
        op: &CounterOp,
    ) -> Result<Verdict, HarnessError> {
        let times = match op {
            CounterOp::Increment => 1,
            CounterOp::IncrementTwice => 2,
        };
        let counter = Self::counter(ctx, w)?;
        for _ in 0..times {
            counter
                .increment(SIGNER)
                .await
                .map_err(HarnessError::Infra)?;
            w.model += 1;
        }
        w.any_incremented = true;
        Ok(Verdict::Accepted)
    }

    fn op_kinds(&self) -> Vec<CounterOpKind> {
        vec![CounterOpKind::Increment, CounterOpKind::IncrementTwice]
    }

    fn generate_op(&self, _rng: &mut Prng, _w: &CounterWorld, kind: CounterOpKind) -> CounterOp {
        match kind {
            CounterOpKind::Increment => CounterOp::Increment,
            CounterOpKind::IncrementTwice => CounterOp::IncrementTwice,
        }
    }

    // Bias toward single increments (25% double).
    fn generate(&self, rng: &mut Prng, w: &CounterWorld) -> CounterOp {
        let kind = if rng.chance(0.25) {
            CounterOpKind::IncrementTwice
        } else {
            CounterOpKind::Increment
        };
        self.generate_op(rng, w, kind)
    }

    fn invariants(&self) -> Vec<CounterInv> {
        vec![CounterInv::CountMatchesModel]
    }

    async fn check(&self, ctx: &mut Ctx, w: &CounterWorld, inv: &CounterInv) -> CheckOutcome {
        match inv {
            CounterInv::CountMatchesModel => {
                if !w.any_incremented {
                    return CheckOutcome::skipped("no increment applied yet");
                }
                let counter = match Self::counter(ctx, w) {
                    Ok(c) => c,
                    Err(e) => return CheckOutcome::violated(e.to_string()),
                };
                match counter.count().await {
                    Ok(n) if n == w.model => CheckOutcome::Held,
                    Ok(n) => CheckOutcome::violated(format!("chain {n} != model {}", w.model)),
                    Err(e) => CheckOutcome::violated(e.to_string()),
                }
            }
        }
    }
}

/// Fund the signer and deploy a fresh `Counter` on `chain` under `label`, returning the primed
/// world.
async fn deploy_and_prime(ctx: &Ctx, label: &str) -> Result<CounterWorld, HarnessError> {
    let mut chain = ctx.chain(label)?;
    fund_user(&mut chain, WalletLabel::wrap(SIGNER)).await;
    let counter = Counter::new(chain);
    counter.setup(SIGNER).await.map_err(HarnessError::Infra)?;
    let addr = counter.address().ok_or_else(|| {
        HarnessError::Infra(CrossVmError::wallet(format!(
            "{label}: setup recorded no address"
        )))
    })?;
    Ok(CounterWorld {
        label: label.to_string(),
        addr,
        model: 0,
        any_incremented: false,
    })
}

/// Build the live env (counter deployed on one mock chain built by `chain`) under `label`, and the
/// primed world. The attribute-macro tests call this via their per-crate `counter_setup`; the
/// closure supplies the VM preset so the caller names it once.
pub async fn setup_on(
    label: &str,
    chain: impl FnOnce(Rc<WalletFactory>) -> AnyChain,
) -> Result<(Ctx, CounterWorld), HarnessError> {
    crate::init_tracing();
    let wallets = crate::wallets::test_wallets();
    let mut env = MultiChainEnv::new("counter-harness", wallets.clone());
    env.inject(label, chain(wallets.clone()));
    let ctx = Ctx::new(env.start().await?);
    let world = deploy_and_prime(&ctx, label).await?;
    Ok((ctx, world))
}

/// The config-driven counterpart of [`setup_on`], registered with the `cross-vm` CLI. When the
/// loaded TOML declares a `[[chain]]`, this builds the first declared chain via [`build_chain`] and
/// operates on it (a single-VM harness uses exactly one chain). Otherwise it injects the
/// caller-supplied preset under `label`, honoring `req.target` via `default_chain`.
pub fn config_setup_with(
    req: SetupRequest,
    label: &'static str,
    default_chain: impl Fn(Target, Rc<WalletFactory>) -> AnyChain + 'static,
) -> SetupFuture<'static, CounterWorld> {
    Box::pin(async move {
        crate::init_tracing();
        let wallets = crate::wallets::test_wallets();
        let mut env = MultiChainEnv::new("counter-harness", wallets.clone());

        let used_label = if let Some(spec) = req.chain_specs.first() {
            env.inject(&spec.label, build_chain(spec, wallets.clone())?);
            spec.label.clone()
        } else {
            env.inject(label, default_chain(req.target, wallets.clone()));
            label.to_string()
        };

        let ctx = Ctx::new(env.start().await?);
        let world = deploy_and_prime(&ctx, &used_label).await?;
        Ok((ctx, world))
    })
}
